# Generated by Django 5.0.3 on 2024-04-02 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='file',
            field=models.FileField(upload_to='books/link', validators=[django.core.validators.FileExtensionValidator(['mp3', 'pdf'])]),
        ),
    ]
