# Generated by Django 5.0.4 on 2024-04-28 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_library_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='file',
            field=models.FileField(upload_to='link/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'mp4', 'pdf'])]),
        ),
    ]
