# Generated by Django 5.0.4 on 2024-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_subscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses/media'),
        ),
        migrations.AlterField(
            model_name='course',
            name='limit_booking',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
