# Generated by Django 5.0.3 on 2024-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_result_id', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('program_group', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
