# Generated by Django 4.2.7 on 2024-03-13 08:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0002_alter_user_info_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SY'),
        ),
    ]
