# Generated by Django 4.2.7 on 2024-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0003_alter_user_info_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phonenumber',
            field=models.CharField(max_length=13),
        ),
    ]
