# Generated by Django 4.2.7 on 2024-03-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_user', '0004_alter_user_info_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='ERB_Student_Id',
            new_name='ERP_Student_Id',
        ),
    ]
